export enum AuditAction {
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  PRODUCT_DELETED = 'PRODUCT_DELETED',
  CATEGORY_DELETED = 'CATEGORY_DELETED',
  USER_DELETED = 'USER_DELETED',
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
}
